name: Build Specified Adapter

on:
  workflow_call:
    inputs:
      adapter:
        required: true
        type: string

jobs:
  build-adapter:
    name: Build ${{ github.event.inputs.adapter }} Adapter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/${{ github.event.inputs.adapter }}
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/${{ github.event.inputs.adapter }}
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.adapter }}.jar
          path: adapters/${{ github.event.inputs.adapter }}/build/libs/${{ github.event.inputs.adapter }}.jar
