name: typewriter
description: Visual quest configuration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  collection:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  graphview: ^1.1.1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  auto_size_text: ^3.0.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.3.0
  icon_forest: ^1.1.8
  rive: ^0.10.0
  dropdown_search: ^5.0.5
  tuple: ^2.0.1
  material_floating_search_bar: ^0.3.7
  fuzzy: ^0.4.0-nullsafety.0
  auto_route: ^5.0.4
  theme_json_converter: ^0.1.0
  collapsible: ^1.0.0
  riverpod_annotation: ^1.1.1
  ktx: ^1.1.6
  # Keep this as the older one since we use SocketIO v2 on the server.
  socket_io_client: 1.0.2
  clipboard: ^0.1.3
  dotted_border: ^2.0.0+3
  flutter_svg: ^1.1.6
  color: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  icons_launcher: ^2.0.6
  auto_route_generator: ^5.0.3
  riverpod_generator: ^1.1.1

icons_launcher:
  image_path: "assets/Typewriter.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/materials/