name: typewriter
description: Visual quest configuration
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  collection:
  stack_trace:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  graphview: ^1.2.0
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  rive: ^0.11.2
  fuzzy: ^0.4.0-nullsafety.0
  auto_route: ^7.4.0
  collapsible: ^1.0.0
  riverpod_annotation: ^2.1.1
  ktx: ^1.1.6
  # Keep this as the older one since we use SocketIO v2 on the server.
  socket_io_client: 1.0.2
  clipboard: ^0.1.3
  dotted_border: ^2.0.0+3
  flutter_svg: ^2.0.6
  color: ^3.0.0
  duration: ^3.0.12
  flutter_animate: ^4.1.1+1
  text_scroll: ^0.2.0
  url_launcher: ^6.1.11
  http:
  audioplayers: ^4.1.0
  collection_ext: ^1.0.0
  tinycolor2: ^3.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  icons_launcher: ^2.1.1
  auto_route_generator: ^7.1.1
  riverpod_generator: ^2.2.3
  custom_lint:
  riverpod_lint: ^1.3.2

icons_launcher:
  image_path: "assets/Typewriter.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/materials/
