name: Build Specified Adapter

on:
  workflow_call:
    inputs:
      adapter:
        required: true
        type: string
        description: The name of the adapter to build

jobs:
  build-adapter:
    name: Build ${{ inputs.adapter }} Adapter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: |
          ls
          pwd
          ./gradlew test --scan
        working-directory: ./adapters/${{ inputs.adapter }}
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/${{ inputs.adapter }}
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.adapter }}.jar
          path: adapters/${{ inputs.adapter }}/build/libs/${{ inputs.adapter }}.jar
