name: Build Typewriter Plugin

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Run tests
        run: flutter test
        working-directory: ./app
      - name: Build web app
        run: flutter build web --release --no-tree-shake-icons
        working-directory: ./app
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          java-version: 17
      - name: Test Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --scan
          build-root-directory: ./plugin
          java-version: 17
      - name: Build Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildRelease --scan
          build-root-directory: ./plugin
          java-version: 17
      - name: Upload Plugin
        uses: actions/upload-artifact@v2
        with:
          name: typewriter.jar
          path: plugin/build/libs/typewriter.jar
