name: Build Artifacts

on:
  push:
#    branches:
#      - main

jobs:
  build-app-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        working-directory: ./app
        run: |
          flutter pub get
          sudo apt install clang ninja-build libgtk-3-dev -y

      - name: Build AppImage
        working-directory: ./app
        run: flutter build linux --release
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: linux.zip
          directory: ./app/build/linux/x64/release/bundle
      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          path: ./app/build/linux/x64/release/bundle/linux.zip

  build-app-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get
      - name: Build Windows
        working-directory: ./app
        run: flutter build windows --release
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: windows.zip
          directory: ./app/build/windows/runner/Release
      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          path: ./app/build/windows/runner/Release/windows.zip

  build-app-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get
      - name: Build MacOS
        working-directory: ./app
        run: flutter build macos --release
      - name: Bundle MacOS
        working-directory: ./app/build/macos/Build/Products/Release
        run: |
          brew install create-dmg
          
          create-dmg \
            --volname "Typewriter" \
            --window-pos 200 120 \
            --window-size 800 529 \
            --icon-size 130 \
            --text-size 14 \
            --icon "typewriter.app" 260 250 \
            --hide-extension "typewriter.app" \
            --app-drop-link 540 250 \
            --hdiutil-quiet \
            "Typewriter.dmg" \
            "typewriter.app"
      - name: Upload MacOS
        uses: actions/upload-artifact@v2
        with:
          path: ./app/build/macos/Build/Products/Release/Typewriter.dmg
