name: Build Jars

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      plugin: ${{ steps.changes.outputs.plugin }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            plugin: 
              - plugin/**
              - app/**
            basic_adapter:
              - adapters/BasicAdapter/**
            citizens_adapter:
              - adapters/CitizensAdapter/**
            combat_log_x_adapter:
              - adapters/CombatLogXAdapter/**
            mythic_mobs_adapter:
              - adapters/MythicMobsAdapter/**
            rpg_regions_adapter:
              - adapters/RPGRegionsAdapter/**
            superior_skyblock_adapter:
              - adapters/SuperiorSkyblockAdapter/**
            vault_adapter:
              - adapters/VaultAdapter/**
            worldguard_adapter:
              - adapters/WorldGuardAdapter/**

  build-plugin:
    name: Build Typewriter Plugin
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.plugin == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "dev"
      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Run tests
        run: flutter test
        working-directory: ./app
      - name: Build web app
        run: flutter build web --release
        working-directory: ./app
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Plugin
        run: ./gradlew test --scan
        working-directory: ./plugin
      - name: Build Plugin
        run: ./gradlew buildRelease --scan
        working-directory: ./plugin
      - name: Upload Plugin
        uses: actions/upload-artifact@v2
        with:
          name: typewriter.jar
          path: plugin/build/libs/typewriter.jar

  build-adapter-basic:
    name: Build Basic Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.basic_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/BasicAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/BasicAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: BasicAdapter.jar
          path: adapters/BasicAdapter/build/libs/BasicAdapter.jar

  build-adapter-citizens:
    name: Build Citizens Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.citizens_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/CitizensAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/CitizensAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: CitizensAdapter.jar
          path: adapters/CitizensAdapter/build/libs/CitizensAdapter.jar


  build-adapter-combat-log-x:
    name: Build CombatLogX Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.combat_log_x_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/CombatLogXAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/CombatLogXAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: CombatLogXAdapter.jar
          path: adapters/CombatLogXAdapter/build/libs/CombatLogXAdapter.jar

  build-adapter-mythic-mobs:
    name: Build MythicMobs Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.mythic_mobs_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/MythicMobsAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/MythicMobsAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: MythicMobsAdapter.jar
          path: adapters/MythicMobsAdapter/build/libs/MythicMobsAdapter.jar

  build-adapter-rpg-regions:
    name: Build RPGRegions Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.rpg_regions_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/RPGRegionsAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/RPGRegionsAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: RPGRegionsAdapter.jar
          path: adapters/RPGRegionsAdapter/build/libs/RPGRegionsAdapter.jar

  build-adapter-superior-skyblock:
    name: Build SuperiorSkyblock Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.superior_skyblock_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/SuperiorSkyblockAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/SuperiorSkyblockAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: SuperiorSkyblockAdapter.jar
          path: adapters/SuperiorSkyblockAdapter/build/libs/SuperiorSkyblockAdapter.jar

  build-adapter-vault:
    name: Build Vault Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.vault_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/VaultAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/VaultAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: VaultAdapter.jar
          path: adapters/VaultAdapter/build/libs/VaultAdapter.jar

  build-adapter-worldguard:
    name: Build WorldGuard Adapter
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.world_guard_adapter == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/WorldGuardAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/WorldGuardAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: WorldGuardAdapter.jar
          path: adapters/WorldGuardAdapter/build/libs/WorldGuardAdapter.jar

