name: Build Jars

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      plugin: ${{ steps.changes.outputs.plugin }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            plugin: 
              - plugin/**
              - app/**

  build-plugin:
    name: Build Typewriter Plugin
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.plugin == 'true' }} 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Run tests
        run: flutter test
        working-directory: ./app
      - name: Build web app
        run: flutter build web --release
        working-directory: ./app
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Plugin
        run: ./gradlew test --scan
        working-directory: ./plugin
      - name: Build Plugin
        run: ./gradlew buildRelease --scan
        working-directory: ./plugin
      - name: Upload Plugin
        uses: actions/upload-artifact@v2
        with:
          name: typewriter.jar
          path: plugin/build/libs/typewriter.jar
